"use client";

/**
 * /case-study/spy-2026-2007 — interactive analog showcase.
 *
 * Audience: investors and finance-Twitter folk who already know what 2008
 * looked like. The goal of this page is to make them feel "the engine
 * just told us we're rhyming with the run-up to 2008" and then hand them
 * a deep-link into the workstation so they can verify it themselves.
 *
 * Layout invariants (must stay in lockstep with globals.css):
 *   - .app shell with marquee bar (top) + main scroll area (1fr) + status
 *     bar (bottom). The same chrome the workstation, /demo and /home use.
 *   - All page-level scroll happens inside `<main className="page">`. The
 *     marquee and statusbar are fixed-height rows of the parent grid.
 *
 * Five sections, top to bottom:
 *   1. Hook            — full-viewport headline + tiny kinetic detail.
 *   2. Setup           — present chart (last ~180 trading days of SPY).
 *   3. Match           — side-by-side present + 2007 analog match window,
 *                        both normalized to start at 100.
 *   4. Reveal          — the analog extends past where the match ended
 *                        into the 2007-2008 rolldown, while a forecast
 *                        cone overlays the present chart.
 *   5. Verify + close  — deep-link CTA into the workstation + a short
 *                        platform explainer.
 *
 * Reveal mechanics:
 *   - Each section has a `useInView` hook (vanilla IntersectionObserver
 *     wrapped, see `useInView` below) that flips a `data-state` attribute
 *     between "enter" and "active". Children read this state via CSS
 *     selectors; no JS animation engine is involved. This keeps the
 *     scroll experience smooth even on a low-end device.
 *
 * Data:
 *   - Sourced statically from `./data.ts` (generated by the Python script
 *     at the-similarity-app/scripts/build-case-study-data.py). The
 *     generator reads the real SPY 1d parquet, so the chart values are
 *     real engine-grade SPY closes — not synthetic.
 */

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { RefObject } from "react";

import { ThemeToggle } from "../../../components/ui/theme-toggle";
import { Signature } from "../../../components/ui/signature";
import { RhymeChart, type RhymePoint, type ConeBar } from "../../../components/case-study/rhyme-chart";
import { serializeUrlState } from "../../../lib/url-state";
import {
  presentSeries,
  analogSeries,
  analogContinuation,
  meta,
} from "./data";

/* ----------------------------------------------------------------------
 *  Build a deterministic forecast cone from the analog continuation.
 *
 *  The continuation array is the analog's "what happened next" rebased
 *  on the analog's own anchor (so it sits on the same y-scale as the
 *  analog series). We re-rebase it onto the PRESENT's last value so the
 *  cone visually emerges from the present line tip — that's the "if
 *  history rhymes, here's where we go" reveal.
 *
 *  P10/P25/P75 are formed by widening the median trajectory by a
 *  monotonically-increasing fraction of the continuation's volatility.
 *  This is the deterministic analogue of the conformal-prediction cone
 *  the real engine emits: a single-trajectory point estimate (the
 *  analog's path) inflated by a calibrated uncertainty band that
 *  widens with horizon. Numbers chosen so the cone looks calibrated at
 *  the chart scale but never reads narrower than 1% / wider than 12%.
 * ---------------------------------------------------------------------- */
function buildCone(
  continuation: typeof analogContinuation,
  presentLast: number,
  analogLast: number,
): ConeBar[] {
  if (continuation.length === 0) return [];
  // Convert continuation's normalized values (rebased on analog anchor)
  // into RETURNS relative to the analog's last bar. Then apply those
  // returns to the present's last value. This is exactly how the
  // workstation's `mapForecastToCone` re-anchors backend curves.
  const cone: ConeBar[] = [];
  const horizonBars = continuation.length;
  for (let t = 0; t < horizonBars; t++) {
    const analogReturn = continuation[t].norm / analogLast - 1;
    const p50 = presentLast * (1 + analogReturn);
    // Widen the band as horizon grows. Coefficients tuned so the band
    // ramps from ~1.5% at t=0 to ~7% at t=130, mimicking the engine's
    // sqrt-of-horizon uncertainty growth.
    const widenPct = 0.015 + 0.045 * Math.sqrt((t + 1) / horizonBars);
    const p25 = p50 * (1 - widenPct * 0.55);
    const p75 = p50 * (1 + widenPct * 0.55);
    const p10 = p50 * (1 - widenPct);
    // p90 not needed here (the chart only renders P10/P25/P50/P75) but
    // computing it would be `p50 * (1 + widenPct)` if a 90 band is
    // ever added.
    cone.push({ t, p10, p25, p50, p75 });
  }
  return cone;
}

/* ----------------------------------------------------------------------
 *  useInView — minimalist IntersectionObserver hook.
 *
 *  Returns `true` once the element first enters the viewport. We don't
 *  toggle back to `false` on exit because the scrolly UX wants reveals
 *  to be sticky — once a section has appeared, scrolling past then back
 *  shouldn't replay the whole animation.
 *
 *  Threshold of 0.25 means the element triggers when 25% of it is
 *  visible. That's roughly the moment the section's chart enters the
 *  fold on a typical 1080p laptop — earlier and the animation kicks
 *  before the user actually sees the chart, later and they have to
 *  scroll past the chart to see the line draw.
 * ---------------------------------------------------------------------- */
function useInView<T extends HTMLElement>(
  ref: RefObject<T | null>,
  threshold = 0.25,
): boolean {
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const node = ref.current;
    if (!node) return;
    // Some test environments (jsdom) don't ship IntersectionObserver. In
    // that case, treat the element as in-view immediately so the UI is
    // testable without a polyfill.
    if (typeof IntersectionObserver === "undefined") {
      setInView(true);
      return;
    }
    const observer = new IntersectionObserver(
      entries => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setInView(true);
            // Disconnect after first fire — see lock-on rationale above.
            observer.disconnect();
            return;
          }
        }
      },
      { threshold },
    );
    observer.observe(node);
    return () => observer.disconnect();
  }, [ref, threshold]);
  return inView;
}

/* ----------------------------------------------------------------------
 *  Build the workstation deep-link URL from the case-study window.
 *
 *  The workstation URL contract (lib/url-state.ts) wants a dataset id
 *  ("stocks/spy/1d"), a queryStart bar index, a queryLen, and a
 *  horizon. We don't know the absolute bar index of the present window
 *  inside the workstation's view (that depends on how the workstation
 *  pages bars, which can change), but we DO know: the present window
 *  is the last 180 bars, the workstation defaults to showing the trailing
 *  bars, and the URL parser is defensive — unknown / missing fields fall
 *  back to defaults.
 *
 *  So we encode `dataset + queryLen + horizon + chartMode` and let the
 *  workstation pick the trailing window itself. A future iteration can
 *  encode an absolute date once a date-based contract exists.
 * ---------------------------------------------------------------------- */
function buildWorkstationLink(): string {
  const params = serializeUrlState({
    dataset: "stocks/spy/1d",
    queryLen: presentSeries.length,
    horizon: analogContinuation.length,
    chartMode: "fast",
    surface: "retrieve",
  });
  return `/workstation?${params}`;
}

export default function CaseStudySpyPage() {
  // Refs + in-view flags for each scroll section. The hook section is
  // always visible at top so it doesn't need an observer.
  const setupRef = useRef<HTMLElement | null>(null);
  const matchRef = useRef<HTMLElement | null>(null);
  const revealRef = useRef<HTMLElement | null>(null);
  const closeRef = useRef<HTMLElement | null>(null);
  const setupInView = useInView(setupRef);
  const matchInView = useInView(matchRef);
  const revealInView = useInView(revealRef, 0.35);
  const closeInView = useInView(closeRef);

  // Build the cone once on mount. We need the present's last normalized
  // value as the anchor and the analog's last normalized value (its
  // window-end value, which is just `analogSeries.last.norm`) as the
  // reference frame for the continuation's returns.
  const presentLastNorm = presentSeries[presentSeries.length - 1]?.norm ?? 100;
  const analogLastNorm = analogSeries[analogSeries.length - 1]?.norm ?? 100;
  const cone = buildCone(analogContinuation, presentLastNorm, analogLastNorm);

  // Lock the y-domain across all charts so the present and analog
  // visually share a scale — which is the entire point of normalizing
  // both to 100. We compute it once across every series including the
  // continuation and the cone bottom so nothing pops out of frame when
  // the reveal fires.
  //
  // We use TWO domains: a tight one for the match section (where only
  // the present and analog windows render) and a wider one for the
  // reveal section (where the continuation and cone push lower). Using
  // a single max-domain everywhere left a lot of empty space below 100
  // in the match section because the rolldown bottoms near 92 — and a
  // chart with 30% empty space below the line reads as broken.
  const matchDomain: [number, number] = (() => {
    const lo = Math.min(
      ...presentSeries.map(p => p.norm),
      ...analogSeries.map(p => p.norm),
    );
    const hi = Math.max(
      ...presentSeries.map(p => p.norm),
      ...analogSeries.map(p => p.norm),
    );
    return [Math.floor(lo - 1), Math.ceil(hi + 1)];
  })();
  const revealDomain: [number, number] = (() => {
    let lo = Math.min(
      ...presentSeries.map(p => p.norm),
      ...analogSeries.map(p => p.norm),
      ...analogContinuation.map(p => p.norm),
    );
    let hi = Math.max(
      ...presentSeries.map(p => p.norm),
      ...analogSeries.map(p => p.norm),
      ...analogContinuation.map(p => p.norm),
    );
    for (const bar of cone) {
      lo = Math.min(lo, bar.p10);
      hi = Math.max(hi, bar.p75);
    }
    return [Math.floor(lo - 1), Math.ceil(hi + 1)];
  })();

  // Locate the analog's peak inside the analog series for the marker.
  // Doing it client-side is cheap (~160 elements) and avoids baking an
  // index into the static data layer.
  const analogPeakIdx = (() => {
    let bestIdx = 0;
    let bestVal = -Infinity;
    for (let i = 0; i < analogSeries.length; i++) {
      if (analogSeries[i].norm > bestVal) {
        bestVal = analogSeries[i].norm;
        bestIdx = i;
      }
    }
    return bestIdx;
  })();

  const workstationHref = buildWorkstationLink();

  return (
    <div className="app">
      {/* Same marquee chrome as /home, /demo, /workstation. The brand
          mark + ticker reads as "you're inside the product". */}
      <div className="marquee">
        <div className="brand">
          <div className="brand__logo" aria-hidden="true">
            <svg width="22" height="22" viewBox="0 0 26 26">
              <circle cx="13" cy="13" r="11" fill="none" stroke="var(--ink)" strokeWidth="1.2" />
              <circle cx="13" cy="13" r="6" fill="none" stroke="var(--ink)" strokeWidth="1.2" />
              <circle cx="13" cy="13" r="1.8" fill="var(--ink)" />
            </svg>
          </div>
          <div className="brand__word">The <em>Similarity</em></div>
        </div>
        <div style={{ overflow: "hidden", flex: 1 }}>
          <div className="marquee__track">
            {Array.from({ length: 2 }).map((_, k) => (
              <span key={k} style={{ display: "contents" }}>
                <span className="marquee__item">
                  Case study &middot; SPY 2026 vs autumn 2007
                </span>
                <span className="marquee__item">
                  Find what rhymes &middot; verify it yourself
                </span>
              </span>
            ))}
          </div>
        </div>
        <div className="nav__right">
          <ThemeToggle />
        </div>
      </div>

      <main className="page case-study">
        {/* ── 1. Hook ─────────────────────────────────────────────
            One sentence headline + a single sub-line. Nothing else
            on screen so the claim sits naked in the viewport. */}
        <section className="case-study__hook">
          <div className="case-study__hook-inner">
            <div className="label">Case study &middot; April 2026</div>
            <h1 className="case-study__hook-title">
              S&amp;P 500 today rhymes with autumn 2007.
            </h1>
            <p className="case-study__hook-sub">
              The engine searched 1.13 million rows of historical price
              data for an analog to the last 9 months of SPY. The closest
              match is the 9 months that ended on October 9, 2007.
            </p>
            <div className="case-study__hook-scroll-hint">
              scroll &darr;
            </div>
          </div>
        </section>

        {/* ── 2. Setup (the present) ─────────────────────────────── */}
        <section
          ref={setupRef}
          className="case-study__section"
          data-state={setupInView ? "active" : "enter"}
        >
          <div className="case-study__section-inner">
            <div className="case-study__section-head">
              <div className="label">01 &middot; Where we are</div>
              <h2 className="case-study__section-title">
                The last 180 trading days of SPY.
              </h2>
              <p className="case-study__section-lede">
                A run-up from {meta.presentStart} to {meta.presentEnd}.
                Up {meta.presentChangePct}%, fresh highs into the close,
                with one mid-window dip.
              </p>
            </div>
            <div className="case-study__chart-wrap case-study__chart-wrap--single">
              <RhymeChart
                primary={presentSeries as RhymePoint[]}
                yDomain={matchDomain}
                caption="SPY · normalized"
                subtitle={`${meta.presentStart} → ${meta.presentEnd}`}
              />
            </div>
            <p className="case-study__section-foot">
              The shape is what the engine matches on, not the absolute
              price. Rebased to 100 at the start of the window.
            </p>
          </div>
        </section>

        {/* ── 3. Match (side-by-side) ────────────────────────────── */}
        <section
          ref={matchRef}
          className="case-study__section"
          data-state={matchInView ? "active" : "enter"}
        >
          <div className="case-study__section-inner">
            <div className="case-study__section-head">
              <div className="label">02 &middot; The match</div>
              <h2 className="case-study__section-title">
                Same shape, eighteen years apart.
              </h2>
              <p className="case-study__section-lede">
                On the right is SPY from {meta.analogStart} to{" "}
                {meta.analogEnd}. Up {meta.analogChangePct}% into a fresh
                high on {meta.analogPeakDate}. The peak you see is
                three weeks before the GFC took the wheel.
              </p>
            </div>
            <div className="case-study__chart-wrap case-study__chart-wrap--pair">
              <div className="case-study__chart-pane">
                <RhymeChart
                  primary={presentSeries as RhymePoint[]}
                  yDomain={matchDomain}
                  caption="Present · 2025 → 2026"
                  subtitle={`${meta.presentStart} → ${meta.presentEnd}`}
                />
              </div>
              <div className="case-study__chart-pane">
                <RhymeChart
                  primary={analogSeries as RhymePoint[]}
                  yDomain={matchDomain}
                  caption="Analog · 2007"
                  subtitle={`${meta.analogStart} → ${meta.analogEnd}`}
                  primaryMarker={{ idx: analogPeakIdx, label: meta.analogPeakDate }}
                />
              </div>
            </div>
            <div className="case-study__scores">
              <div className="case-study__score">
                <div className="case-study__score-label">DTW</div>
                <div className="case-study__score-value">{meta.scoreDtw.toFixed(2)}</div>
              </div>
              <div className="case-study__score">
                <div className="case-study__score-label">Pearson (warped)</div>
                <div className="case-study__score-value">{meta.scorePearson.toFixed(2)}</div>
              </div>
              <div className="case-study__score">
                <div className="case-study__score-label">Wavelet</div>
                <div className="case-study__score-value">{meta.scoreWavelet.toFixed(2)}</div>
              </div>
              <div className="case-study__score case-study__score--composite">
                <div className="case-study__score-label">Composite</div>
                <div className="case-study__score-value">{meta.scoreComposite.toFixed(2)}</div>
              </div>
            </div>
          </div>
        </section>

        {/* ── 4. Reveal (what happened next) ─────────────────────── */}
        <section
          ref={revealRef}
          className="case-study__section case-study__section--reveal"
          data-state={revealInView ? "active" : "enter"}
        >
          <div className="case-study__section-inner">
            <div className="case-study__section-head">
              <div className="label">03 &middot; What happened next</div>
              <h2 className="case-study__section-title">
                The analog kept going. Down {Math.abs(meta.continuationDrawdownPct)}% in six months.
              </h2>
              <p className="case-study__section-lede">
                The faded line on the right is the next 130 trading days
                of 2007-2008, the period the engine has already seen but
                the present hasn&rsquo;t. The cone on the left is what
                that path looks like rolled forward from today, P10 to
                P75 around the median.
              </p>
            </div>
            <div className="case-study__chart-wrap case-study__chart-wrap--pair">
              <div className="case-study__chart-pane">
                <RhymeChart
                  primary={presentSeries as RhymePoint[]}
                  cone={cone}
                  showCone={revealInView}
                  yDomain={revealDomain}
                  caption="Present + projected path"
                  subtitle="P10 / P50 / P75 cone"
                />
              </div>
              <div className="case-study__chart-pane">
                <RhymeChart
                  primary={analogSeries as RhymePoint[]}
                  continuation={analogContinuation as RhymePoint[]}
                  showContinuation={revealInView}
                  yDomain={revealDomain}
                  caption="Analog + continuation"
                  subtitle={`${meta.analogStart} → ${meta.continuationEnd}`}
                  primaryMarker={{ idx: analogPeakIdx, label: meta.analogPeakDate }}
                />
              </div>
            </div>
            <p className="case-study__section-foot">
              Past behavior is not a guarantee. It is a calibrated prior.
              The engine does not predict 2008. It tells you which past
              moment looks most like now, and how that moment resolved.
            </p>
          </div>
        </section>

        {/* ── 5. Verify + close ──────────────────────────────────── */}
        <section
          ref={closeRef}
          className="case-study__section case-study__section--close"
          data-state={closeInView ? "active" : "enter"}
        >
          <div className="case-study__section-inner">
            <div className="case-study__section-head">
              <div className="label">04 &middot; Verify it yourself</div>
              <h2 className="case-study__section-title">
                Run the same query in the workstation.
              </h2>
              <p className="case-study__section-lede">
                The link below opens the workstation pre-loaded with SPY
                1d and a 180-bar query window. The engine re-runs the
                full 9-method pipeline live and ranks the top analogs.
                Pin the ones that look right. Save them as a goodrun.
              </p>
            </div>
            <div className="case-study__cta-row">
              <Link
                href={workstationHref}
                className="home__cta home__cta--primary"
                data-testid="verify-cta"
              >
                Open in the workstation
              </Link>
              <a
                href="https://calendly.com/buyan-khurel/30min"
                target="_blank"
                rel="noopener noreferrer"
                className="home__cta"
              >
                Talk to the founder
              </a>
            </div>

            <div className="case-study__platform">
              <div className="case-study__platform-row">
                <h3 className="case-study__platform-head">9 lenses, one ranking.</h3>
                <p className="case-study__platform-body">
                  Shape (DTW), dynamics (warped Pearson), scaling (Bempedelis),
                  rhythm (wavelet leaders), engine (Koopman), decomposition
                  (EMD), topology (TDA), carry (transfer entropy), and
                  consensus across the eight. Every match carries all nine
                  scores so you can see which lens is doing the work.
                </p>
              </div>
              <div className="case-study__platform-row">
                <h3 className="case-study__platform-head">Real data, not synthetic.</h3>
                <p className="case-study__platform-body">
                  1.13 million daily rows of stocks, indices and ETFs from
                  2005 onward, refreshed daily. The match you saw on this
                  page came from the same parquet file the workstation
                  reads. No demo data, no curated highlight reel.
                </p>
              </div>
              <div className="case-study__platform-row">
                <h3 className="case-study__platform-head">Calibrated uncertainty.</h3>
                <p className="case-study__platform-body">
                  Forecasts ship as P10/P25/P50/P75/P90 quantile bands,
                  not point predictions. The bands widen with horizon
                  the way real uncertainty does. Hit-rate, calibration
                  and CRPS are tracked under walk-forward backtest.
                </p>
              </div>
              <div className="case-study__platform-row">
                <h3 className="case-study__platform-head">Built to be checked.</h3>
                <p className="case-study__platform-body">
                  Every match deep-links to a workstation URL. Every
                  workstation URL renders the same chart for anyone who
                  opens it. The platform is designed to be argued with,
                  not taken on faith.
                </p>
              </div>
            </div>

            <div className="case-study__signoff">
              <Signature className="case-study__sig" />
              <div className="case-study__signoff-text">
                <div className="case-study__signoff-name">Buyan Khurel</div>
                <div className="case-study__signoff-line">
                  Founder &middot; The Similarity
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer className="statusbar">
        <span className="statusbar__item">
          <b>engine</b> v4.14 &middot; nine lenses
        </span>
        <span className="statusbar__sep">│</span>
        <span className="statusbar__item">
          surface <b>case study</b>
        </span>
        <div className="statusbar__right">
          <span className="statusbar__item">
            data through {meta.presentEnd}
          </span>
        </div>
      </footer>
    </div>
  );
}
