"""ReviewArtifact — structured review decision for a finance run.

A :class:`ReviewArtifact` captures a human-or-agent review decision on a
finance run (identified by ``run_id``). It is the bridge between automated
risk analysis (see :mod:`the_similarity.finance.risk_flags`) and the
downstream decision layer (strategy execution, portfolio alerts).

Lifecycle
---------
1. A finance run completes and produces a ``RunRecord`` with a summary dict.
2. Risk flags are auto-detected via :func:`detect_risk_flags`.
3. A signal summary is generated via :func:`generate_signal_summary`.
4. A :class:`ReviewArtifact` is created with status ``PENDING``.
5. A reviewer (human or agent) updates the status to APPROVED / FLAGGED /
   REJECTED with notes.
6. Post-hoc, ``realized_outcome`` may be filled once the forward period
   elapses.

Immutability
------------
Once written to disk or the registry, a ReviewArtifact should be treated
as append-only: the ``updated_at`` field tracks the most recent mutation,
but ``review_id`` is stable. To revise a review decision, update the
existing artifact (bump ``updated_at``) rather than creating a new one.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

from the_similarity.platform.artifacts import iso_now


class ReviewStatus(str, Enum):
    """Lifecycle state of a review decision.

    Inherits from ``str`` so JSON round-tripping is trivial (matches the
    pattern used by ``RunStatus`` in ``the_similarity.platform.contracts``).

    Members
    -------
    PENDING:
        Review created but no decision rendered yet. Default for
        auto-generated reviews awaiting human confirmation.
    APPROVED:
        Reviewer has confirmed the signal is trustworthy and actionable.
    FLAGGED:
        Signal has issues but is not outright rejected. Requires
        additional scrutiny before acting.
    REJECTED:
        Signal is unreliable or the run had critical issues. Do not
        act on this run's outputs.
    """

    PENDING = "pending"
    APPROVED = "approved"
    FLAGGED = "flagged"
    REJECTED = "rejected"


@dataclass
class ReviewArtifact:
    """Structured review decision for a finance run.

    Fields
    ------
    review_id:
        UUID4 hex (no dashes). Globally unique across all reviews.
    run_id:
        FK to the finance ``RunRecord.run_id`` being reviewed.
    reviewer:
        Identifier for who produced this review. Agent ID (e.g.
        ``"review-agent-v1"``) or human email.
    status:
        Current review status. See :class:`ReviewStatus`.
    signal_summary:
        1-3 sentence human-readable summary of what the run found.
        Generated by :func:`generate_signal_summary` or written manually.
    trust_decision:
        High-level trust verdict: ``"TRUSTED"``, ``"REVIEW"``, or
        ``"REJECTED"``. May come from Agent 1's TrustArtifact or be
        manually overridden by the reviewer.
    calibration_context:
        Snapshot of calibration metrics at review time. Preserved so
        the review decision can be audited against the state that
        existed when it was made.
    risk_flags:
        List of short string risk flag constants (e.g.
        ``["low_trial_count", "poor_calibration"]``). Auto-detected
        by :func:`detect_risk_flags` or manually added.
    notes:
        Free-form reviewer notes. May include reasoning, caveats,
        or instructions for downstream consumers.
    realized_outcome:
        Filled post-hoc once the forward period elapses. Expected
        keys: ``actual_return``, ``hit``, ``notes``. ``None`` until
        the outcome is known.
    created_at:
        ISO-8601 UTC timestamp of initial creation.
    updated_at:
        ISO-8601 UTC timestamp of most recent update. ``None`` if
        the artifact has never been updated after creation.
    """

    review_id: str
    run_id: str
    reviewer: str
    status: ReviewStatus
    signal_summary: str
    trust_decision: str
    calibration_context: Dict[str, Any] = field(default_factory=dict)
    risk_flags: List[str] = field(default_factory=list)
    notes: str = ""
    realized_outcome: Optional[Dict[str, Any]] = None
    created_at: str = field(default_factory=iso_now)
    updated_at: Optional[str] = None

    # -- factories ---------------------------------------------------------

    @staticmethod
    def new_review_id() -> str:
        """Generate a new UUID4 hex review ID (no dashes, 32 chars)."""
        return uuid.uuid4().hex

    # -- serialization -----------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-safe dict suitable for ``json.dumps`` or the registry.

        Enum fields serialize to their string value; all other fields pass
        through unchanged. Nested dicts/lists are NOT deep-copied — we
        treat written artifacts as immutable post-serialization.
        """
        return {
            "review_id": self.review_id,
            "run_id": self.run_id,
            "reviewer": self.reviewer,
            "status": self.status.value,
            "signal_summary": self.signal_summary,
            "trust_decision": self.trust_decision,
            "calibration_context": self.calibration_context,
            "risk_flags": self.risk_flags,
            "notes": self.notes,
            "realized_outcome": self.realized_outcome,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "ReviewArtifact":
        """Reconstruct a :class:`ReviewArtifact` from a JSON-decoded dict.

        Coerces ``status`` from its string value to the enum member.
        Unknown keys are ignored for forward compatibility.

        Raises
        ------
        KeyError:
            If required fields (``review_id``, ``run_id``, ``reviewer``,
            ``status``, ``signal_summary``, ``trust_decision``) are missing.
        ValueError:
            If ``status`` is not a valid :class:`ReviewStatus` member.
        """
        # Coerce status from string to enum — accept both enum and string
        raw_status = d["status"]
        if isinstance(raw_status, ReviewStatus):
            status = raw_status
        else:
            status = ReviewStatus(raw_status)

        return cls(
            review_id=d["review_id"],
            run_id=d["run_id"],
            reviewer=d["reviewer"],
            status=status,
            signal_summary=d["signal_summary"],
            trust_decision=d["trust_decision"],
            calibration_context=d.get("calibration_context", {}) or {},
            risk_flags=d.get("risk_flags", []) or [],
            notes=d.get("notes", ""),
            realized_outcome=d.get("realized_outcome"),
            created_at=d.get("created_at", ""),
            updated_at=d.get("updated_at"),
        )

    # -- file I/O ----------------------------------------------------------

    def write_review(self, path: str | Path) -> Path:
        """Write this review artifact to a JSON file on disk.

        Parameters
        ----------
        path:
            File path to write. Parent directories are created if missing.

        Returns
        -------
        Path:
            The resolved path that was written to.
        """
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            json.dumps(self.to_dict(), indent=2, sort_keys=False),
            encoding="utf-8",
        )
        return out

    @classmethod
    def read_review(cls, path: str | Path) -> "ReviewArtifact":
        """Read a review artifact from a JSON file on disk.

        Parameters
        ----------
        path:
            File path to read.

        Returns
        -------
        ReviewArtifact:
            The deserialized artifact.

        Raises
        ------
        FileNotFoundError:
            If the file does not exist.
        json.JSONDecodeError:
            If the file is not valid JSON.
        """
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls.from_dict(data)


__all__ = ["ReviewArtifact", "ReviewStatus"]
